const IOHOOK_KEY_ESCAPE = 0x0001;
const IOHOOK_KEY_F1 = 0x003B;
const IOHOOK_KEY_F2 = 0x003C;
const IOHOOK_KEY_F3 = 0x003D;
const IOHOOK_KEY_F4 = 0x003E;
const IOHOOK_KEY_F5 = 0x003F;
const IOHOOK_KEY_F6 = 0x0040;
const IOHOOK_KEY_F7 = 0x0041;
const IOHOOK_KEY_F8 = 0x0042;
const IOHOOK_KEY_F9 = 0x0043;
const IOHOOK_KEY_F10 = 0x0044;
const IOHOOK_KEY_F11 = 0x0057;
const IOHOOK_KEY_F12 = 0x0058;
const IOHOOK_KEY_F13 = 0x005B;
const IOHOOK_KEY_F14 = 0x005C;
const IOHOOK_KEY_F15 = 0x005D;
const IOHOOK_KEY_F16 = 0x0063;
const IOHOOK_KEY_F17 = 0x0064;
const IOHOOK_KEY_F18 = 0x0065;
const IOHOOK_KEY_F19 = 0x0066;
const IOHOOK_KEY_F20 = 0x0067;
const IOHOOK_KEY_F21 = 0x0068;
const IOHOOK_KEY_F22 = 0x0069;
const IOHOOK_KEY_F23 = 0x006A;
const IOHOOK_KEY_F24 = 0x006B;
const IOHOOK_KEY_BACKQUOTE = 0x0029;
const IOHOOK_KEY_1 = 0x0002;
const IOHOOK_KEY_2 = 0x0003;
const IOHOOK_KEY_3 = 0x0004;
const IOHOOK_KEY_4 = 0x0005;
const IOHOOK_KEY_5 = 0x0006;
const IOHOOK_KEY_6 = 0x0007;
const IOHOOK_KEY_7 = 0x0008;
const IOHOOK_KEY_8 = 0x0009;
const IOHOOK_KEY_9 = 0x000A;
const IOHOOK_KEY_0 = 0x000B;
const IOHOOK_KEY_MINUS = 0x000C;
const IOHOOK_KEY_EQUALS = 0x000D;
const IOHOOK_KEY_BACKSPACE = 0x000E;
const IOHOOK_KEY_TAB = 0x000F;
const IOHOOK_KEY_CAPS_LOCK = 0x003A;
const IOHOOK_KEY_A = 0x001E;
const IOHOOK_KEY_B = 0x0030;
const IOHOOK_KEY_C = 0x002E;
const IOHOOK_KEY_D = 0x0020;
const IOHOOK_KEY_E = 0x0012;
const IOHOOK_KEY_F = 0x0021;
const IOHOOK_KEY_G = 0x0022;
const IOHOOK_KEY_H = 0x0023;
const IOHOOK_KEY_I = 0x0017;
const IOHOOK_KEY_J = 0x0024;
const IOHOOK_KEY_K = 0x0025;
const IOHOOK_KEY_L = 0x0026;
const IOHOOK_KEY_M = 0x0032;
const IOHOOK_KEY_N = 0x0031;
const IOHOOK_KEY_O = 0x0018;
const IOHOOK_KEY_P = 0x0019;
const IOHOOK_KEY_Q = 0x0010;
const IOHOOK_KEY_R = 0x0013;
const IOHOOK_KEY_S = 0x001F;
const IOHOOK_KEY_T = 0x0014;
const IOHOOK_KEY_U = 0x0016;
const IOHOOK_KEY_V = 0x002F;
const IOHOOK_KEY_W = 0x0011;
const IOHOOK_KEY_X = 0x002D;
const IOHOOK_KEY_Y = 0x0015;
const IOHOOK_KEY_Z = 0x002C;
const IOHOOK_KEY_OPEN_BRACKET = 0x001A;
const IOHOOK_KEY_CLOSE_BRACKET = 0x001B;
const IOHOOK_KEY_BACK_SLASH = 0x002B;
const IOHOOK_KEY_SEMICOLON = 0x0027;
const IOHOOK_KEY_QUOTE = 0x0028;
const IOHOOK_KEY_ENTER = 0x001C;
const IOHOOK_KEY_COMMA = 0x0033;
const IOHOOK_KEY_PERIOD = 0x0034;
const IOHOOK_KEY_SLASH = 0x0035;
const IOHOOK_KEY_SPACE = 0x0039;
const IOHOOK_KEY_PRINTSCREEN = 0x0E37;
const IOHOOK_KEY_SCROLL_LOCK = 0x0046;
const IOHOOK_KEY_PAUSE = 0x0E45;
const IOHOOK_KEY_LESSER_GREATER = 0x0E46;
const IOHOOK_KEY_INSERT = 0x0E52;
const IOHOOK_KEY_DELETE = 0x0E53;
const IOHOOK_KEY_HOME = 0x0E47;
const IOHOOK_KEY_END = 0x0E4F;
const IOHOOK_KEY_PAGE_UP = 0x0E49;
const IOHOOK_KEY_PAGE_DOWN = 0x0E51;
const IOHOOK_KEY_UP = 0xE048;
const IOHOOK_KEY_LEFT = 0xE04B;
const IOHOOK_KEY_CLEAR = 0xE04C;
const IOHOOK_KEY_RIGHT = 0xE04D;
const IOHOOK_KEY_DOWN = 0xE050;
const IOHOOK_KEY_NUM_LOCK = 0x0045;
const IOHOOK_KEY_KP_DIVIDE = 0x0E35;
const IOHOOK_KEY_KP_MULTIPLY = 0x0037;
const IOHOOK_KEY_KP_SUBTRACT = 0x004A;
const IOHOOK_KEY_KP_EQUALS = 0x0E0D;
const IOHOOK_KEY_KP_ADD = 0x004E;
const IOHOOK_KEY_KP_ENTER = 0x0E1C;
const IOHOOK_KEY_KP_SEPARATOR = 0x0053;
const IOHOOK_KEY_KP_1 = 0x004F;
const IOHOOK_KEY_KP_2 = 0x0050;
const IOHOOK_KEY_KP_3 = 0x0051;
const IOHOOK_KEY_KP_4 = 0x004B;
const IOHOOK_KEY_KP_5 = 0x004C;
const IOHOOK_KEY_KP_6 = 0x004D;
const IOHOOK_KEY_KP_7 = 0x0047;
const IOHOOK_KEY_KP_8 = 0x0048;
const IOHOOK_KEY_KP_9 = 0x0049;
const IOHOOK_KEY_KP_0 = 0x0052;
const IOHOOK_KEY_SHIFT_L = 0x002A;
const IOHOOK_KEY_SHIFT_R = 0x0036;
const IOHOOK_KEY_CONTROL_L = 0x001D;
const IOHOOK_KEY_CONTROL_R = 0x0E1D;
const IOHOOK_KEY_ALT_L = 0x0038;
const IOHOOK_KEY_ALT_R = 0x0E38;
const IOHOOK_KEY_META_L = 0x0E5B;
const IOHOOK_KEY_META_R = 0x0E5C;
const IOHOOK_KEY_CONTEXT_MENU = 0x0E5D;
const IOHOOK_KEY_POWER = 0xE05E;
const IOHOOK_KEY_SLEEP = 0xE05F;
const IOHOOK_KEY_WAKE = 0xE063;
const IOHOOK_KEY_MEDIA_PLAY = 0xE022;
const IOHOOK_KEY_MEDIA_STOP = 0xE024;
const IOHOOK_KEY_MEDIA_PREVIOUS = 0xE010;
const IOHOOK_KEY_MEDIA_NEXT = 0xE019;
const IOHOOK_KEY_MEDIA_SELECT = 0xE06D;
const IOHOOK_KEY_MEDIA_EJECT = 0xE02C;
const IOHOOK_KEY_VOLUME_MUTE = 0xE020;
const IOHOOK_KEY_VOLUME_UP = 0xE030;
const IOHOOK_KEY_VOLUME_DOWN = 0xE02E;
const IOHOOK_KEY_APP_MAIL = 0xE06C;
const IOHOOK_KEY_APP_CALCULATOR = 0xE021;
const IOHOOK_KEY_APP_MUSIC = 0xE03C;
const IOHOOK_KEY_APP_PICTURES = 0xE064;
const IOHOOK_KEY_BROWSER_SEARCH = 0xE065;
const IOHOOK_KEY_BROWSER_HOME = 0xE032;
const IOHOOK_KEY_BROWSER_BACK = 0xE06A;
const IOHOOK_KEY_BROWSER_FORWARD = 0xE069;
const IOHOOK_KEY_BROWSER_STOP = 0xE068;
const IOHOOK_KEY_BROWSER_REFRESH = 0xE067;
const IOHOOK_KEY_BROWSER_FAVORITES = 0xE066;
const IOHOOK_KEY_KATAKANA = 0x0070;
const IOHOOK_KEY_UNDERSCORE = 0x0073;
const IOHOOK_KEY_FURIGANA = 0x0077;
const IOHOOK_KEY_KANJI = 0x0079;
const IOHOOK_KEY_HIRAGANA = 0x007B;
const IOHOOK_KEY_YEN = 0x007D;
const IOHOOK_KEY_KP_COMMA = 0x007E;
const IOHOOK_KEY_SUN_HELP = 0xFF75;
const IOHOOK_KEY_SUN_STOP = 0xFF78;
const IOHOOK_KEY_SUN_PROPS = 0xFF76;
const IOHOOK_KEY_SUN_FRONT = 0xFF77;
const IOHOOK_KEY_SUN_OPEN = 0xFF74;
const IOHOOK_KEY_SUN_FIND = 0xFF7E;
const IOHOOK_KEY_SUN_AGAIN = 0xFF79;
const IOHOOK_KEY_SUN_UNDO = 0xFF7A;
const IOHOOK_KEY_SUN_COPY = 0xFF7C;
const IOHOOK_KEY_SUN_INSERT = 0xFF7D;
const IOHOOK_KEY_SUN_CUT = 0xFF7B;
const IOHOOK_KEY_UNDEFINED = 0x0000;
const IOHOOK_MOUSE_NOBUTTON = 0;
const IOHOOK_MOUSE_BUTTON1 = 1;
const IOHOOK_MOUSE_BUTTON2 = 2;
const IOHOOK_MOUSE_BUTTON3 = 3;
const IOHOOK_MOUSE_BUTTON4 = 4;
const IOHOOK_MOUSE_BUTTON5 = 5;
const IOHOOK_KEY_KP_END = 0xEE00 | IOHOOK_KEY_KP_1;
const IOHOOK_KEY_KP_DOWN = 0xEE00 | IOHOOK_KEY_KP_2;
const IOHOOK_KEY_KP_PAGE_DOWN = 0xEE00 | IOHOOK_KEY_KP_3;
const IOHOOK_KEY_KP_LEFT = 0xEE00 | IOHOOK_KEY_KP_4;
const IOHOOK_KEY_KP_CLEAR = 0xEE00 | IOHOOK_KEY_KP_5;
const IOHOOK_KEY_KP_RIGHT = 0xEE00 | IOHOOK_KEY_KP_6;
const IOHOOK_KEY_KP_HOME = 0xEE00 | IOHOOK_KEY_KP_7;
const IOHOOK_KEY_KP_UP = 0xEE00 | IOHOOK_KEY_KP_8;
const IOHOOK_KEY_KP_PAGE_UP = 0xEE00 | IOHOOK_KEY_KP_9;
const IOHOOK_KEY_KP_INSERT = 0xEE00 | IOHOOK_KEY_KP_0;
const IOHOOK_KEY_KP_DELETE = 0xEE00 | IOHOOK_KEY_KP_SEPARATOR;

export const ENUM_TO_IOHOOK = {
  KEY_ESCAPE: IOHOOK_KEY_ESCAPE,
  KEY_F1: IOHOOK_KEY_F1,
  KEY_F2: IOHOOK_KEY_F2,
  KEY_F3: IOHOOK_KEY_F3,
  KEY_F4: IOHOOK_KEY_F4,
  KEY_F5: IOHOOK_KEY_F5,
  KEY_F6: IOHOOK_KEY_F6,
  KEY_F7: IOHOOK_KEY_F7,
  KEY_F8: IOHOOK_KEY_F8,
  KEY_F9: IOHOOK_KEY_F9,
  KEY_F10: IOHOOK_KEY_F10,
  KEY_F11: IOHOOK_KEY_F11,
  KEY_F12: IOHOOK_KEY_F12,
  KEY_F13: IOHOOK_KEY_F13,
  KEY_F14: IOHOOK_KEY_F14,
  KEY_F15: IOHOOK_KEY_F15,
  KEY_F16: IOHOOK_KEY_F16,
  KEY_F17: IOHOOK_KEY_F17,
  KEY_F18: IOHOOK_KEY_F18,
  KEY_F19: IOHOOK_KEY_F19,
  KEY_F20: IOHOOK_KEY_F20,
  KEY_F21: IOHOOK_KEY_F21,
  KEY_F22: IOHOOK_KEY_F22,
  KEY_F23: IOHOOK_KEY_F23,
  KEY_F24: IOHOOK_KEY_F24,
  KEY_BACKQUOTE: IOHOOK_KEY_BACKQUOTE,
  KEY_1: IOHOOK_KEY_1,
  KEY_2: IOHOOK_KEY_2,
  KEY_3: IOHOOK_KEY_3,
  KEY_4: IOHOOK_KEY_4,
  KEY_5: IOHOOK_KEY_5,
  KEY_6: IOHOOK_KEY_6,
  KEY_7: IOHOOK_KEY_7,
  KEY_8: IOHOOK_KEY_8,
  KEY_9: IOHOOK_KEY_9,
  KEY_0: IOHOOK_KEY_0,
  KEY_MINUS: IOHOOK_KEY_MINUS,
  KEY_EQUALS: IOHOOK_KEY_EQUALS,
  KEY_BACKSPACE: IOHOOK_KEY_BACKSPACE,
  KEY_TAB: IOHOOK_KEY_TAB,
  KEY_CAPS_LOCK: IOHOOK_KEY_CAPS_LOCK,
  KEY_A: IOHOOK_KEY_A,
  KEY_B: IOHOOK_KEY_B,
  KEY_C: IOHOOK_KEY_C,
  KEY_D: IOHOOK_KEY_D,
  KEY_E: IOHOOK_KEY_E,
  KEY_F: IOHOOK_KEY_F,
  KEY_G: IOHOOK_KEY_G,
  KEY_H: IOHOOK_KEY_H,
  KEY_I: IOHOOK_KEY_I,
  KEY_J: IOHOOK_KEY_J,
  KEY_K: IOHOOK_KEY_K,
  KEY_L: IOHOOK_KEY_L,
  KEY_M: IOHOOK_KEY_M,
  KEY_N: IOHOOK_KEY_N,
  KEY_O: IOHOOK_KEY_O,
  KEY_P: IOHOOK_KEY_P,
  KEY_Q: IOHOOK_KEY_Q,
  KEY_R: IOHOOK_KEY_R,
  KEY_S: IOHOOK_KEY_S,
  KEY_T: IOHOOK_KEY_T,
  KEY_U: IOHOOK_KEY_U,
  KEY_V: IOHOOK_KEY_V,
  KEY_W: IOHOOK_KEY_W,
  KEY_X: IOHOOK_KEY_X,
  KEY_Y: IOHOOK_KEY_Y,
  KEY_Z: IOHOOK_KEY_Z,
  KEY_OPEN_BRACKET: IOHOOK_KEY_OPEN_BRACKET,
  KEY_CLOSE_BRACKET: IOHOOK_KEY_CLOSE_BRACKET,
  KEY_BACK_SLASH: IOHOOK_KEY_BACK_SLASH,
  KEY_SEMICOLON: IOHOOK_KEY_SEMICOLON,
  KEY_QUOTE: IOHOOK_KEY_QUOTE,
  KEY_ENTER: IOHOOK_KEY_ENTER,
  KEY_COMMA: IOHOOK_KEY_COMMA,
  KEY_PERIOD: IOHOOK_KEY_PERIOD,
  KEY_SLASH: IOHOOK_KEY_SLASH,
  KEY_SPACE: IOHOOK_KEY_SPACE,
  KEY_PRINTSCREEN: IOHOOK_KEY_PRINTSCREEN,
  KEY_SCROLL_LOCK: IOHOOK_KEY_SCROLL_LOCK,
  KEY_PAUSE: IOHOOK_KEY_PAUSE,
  KEY_LESSER_GREATER: IOHOOK_KEY_LESSER_GREATER,
  KEY_INSERT: IOHOOK_KEY_INSERT,
  KEY_DELETE: IOHOOK_KEY_DELETE,
  KEY_HOME: IOHOOK_KEY_HOME,
  KEY_END: IOHOOK_KEY_END,
  KEY_PAGE_UP: IOHOOK_KEY_PAGE_UP,
  KEY_PAGE_DOWN: IOHOOK_KEY_PAGE_DOWN,
  KEY_UP: IOHOOK_KEY_UP,
  KEY_LEFT: IOHOOK_KEY_LEFT,
  KEY_CLEAR: IOHOOK_KEY_CLEAR,
  KEY_RIGHT: IOHOOK_KEY_RIGHT,
  KEY_DOWN: IOHOOK_KEY_DOWN,
  KEY_NUM_LOCK: IOHOOK_KEY_NUM_LOCK,
  KEY_KP_DIVIDE: IOHOOK_KEY_KP_DIVIDE,
  KEY_KP_MULTIPLY: IOHOOK_KEY_KP_MULTIPLY,
  KEY_KP_SUBTRACT: IOHOOK_KEY_KP_SUBTRACT,
  KEY_KP_EQUALS: IOHOOK_KEY_KP_EQUALS,
  KEY_KP_ADD: IOHOOK_KEY_KP_ADD,
  KEY_KP_ENTER: IOHOOK_KEY_KP_ENTER,
  KEY_KP_SEPARATOR: IOHOOK_KEY_KP_SEPARATOR,
  KEY_KP_1: IOHOOK_KEY_KP_1,
  KEY_KP_2: IOHOOK_KEY_KP_2,
  KEY_KP_3: IOHOOK_KEY_KP_3,
  KEY_KP_4: IOHOOK_KEY_KP_4,
  KEY_KP_5: IOHOOK_KEY_KP_5,
  KEY_KP_6: IOHOOK_KEY_KP_6,
  KEY_KP_7: IOHOOK_KEY_KP_7,
  KEY_KP_8: IOHOOK_KEY_KP_8,
  KEY_KP_9: IOHOOK_KEY_KP_9,
  KEY_KP_0: IOHOOK_KEY_KP_0,
  KEY_KP_END: IOHOOK_KEY_KP_END,
  KEY_KP_DOWN: IOHOOK_KEY_KP_DOWN,
  KEY_KP_PAGE_DOWN: IOHOOK_KEY_KP_PAGE_DOWN,
  KEY_KP_LEFT: IOHOOK_KEY_KP_LEFT,
  KEY_KP_CLEAR: IOHOOK_KEY_KP_CLEAR,
  KEY_KP_RIGHT: IOHOOK_KEY_KP_RIGHT,
  KEY_KP_HOME: IOHOOK_KEY_KP_HOME,
  KEY_KP_UP: IOHOOK_KEY_KP_UP,
  KEY_KP_PAGE_UP: IOHOOK_KEY_KP_PAGE_UP,
  KEY_KP_INSERT: IOHOOK_KEY_KP_INSERT,
  KEY_KP_DELETE: IOHOOK_KEY_KP_DELETE,
  KEY_SHIFT_L: IOHOOK_KEY_SHIFT_L,
  KEY_SHIFT_R: IOHOOK_KEY_SHIFT_R,
  KEY_CONTROL_L: IOHOOK_KEY_CONTROL_L,
  KEY_CONTROL_R: IOHOOK_KEY_CONTROL_R,
  KEY_ALT_L: IOHOOK_KEY_ALT_L,
  KEY_ALT_R: IOHOOK_KEY_ALT_R,
  KEY_META_L: IOHOOK_KEY_META_L,
  KEY_META_R: IOHOOK_KEY_META_R,
  KEY_CONTEXT_MENU: IOHOOK_KEY_CONTEXT_MENU,
  KEY_POWER: IOHOOK_KEY_POWER,
  KEY_SLEEP: IOHOOK_KEY_SLEEP,
  KEY_WAKE: IOHOOK_KEY_WAKE,
  KEY_MEDIA_PLAY: IOHOOK_KEY_MEDIA_PLAY,
  KEY_MEDIA_STOP: IOHOOK_KEY_MEDIA_STOP,
  KEY_MEDIA_PREVIOUS: IOHOOK_KEY_MEDIA_PREVIOUS,
  KEY_MEDIA_NEXT: IOHOOK_KEY_MEDIA_NEXT,
  KEY_MEDIA_SELECT: IOHOOK_KEY_MEDIA_SELECT,
  KEY_MEDIA_EJECT: IOHOOK_KEY_MEDIA_EJECT,
  KEY_VOLUME_MUTE: IOHOOK_KEY_VOLUME_MUTE,
  KEY_VOLUME_UP: IOHOOK_KEY_VOLUME_UP,
  KEY_VOLUME_DOWN: IOHOOK_KEY_VOLUME_DOWN,
  KEY_APP_MAIL: IOHOOK_KEY_APP_MAIL,
  KEY_APP_CALCULATOR: IOHOOK_KEY_APP_CALCULATOR,
  KEY_APP_MUSIC: IOHOOK_KEY_APP_MUSIC,
  KEY_APP_PICTURES: IOHOOK_KEY_APP_PICTURES,
  KEY_BROWSER_SEARCH: IOHOOK_KEY_BROWSER_SEARCH,
  KEY_BROWSER_HOME: IOHOOK_KEY_BROWSER_HOME,
  KEY_BROWSER_BACK: IOHOOK_KEY_BROWSER_BACK,
  KEY_BROWSER_FORWARD: IOHOOK_KEY_BROWSER_FORWARD,
  KEY_BROWSER_STOP: IOHOOK_KEY_BROWSER_STOP,
  KEY_BROWSER_REFRESH: IOHOOK_KEY_BROWSER_REFRESH,
  KEY_BROWSER_FAVORITES: IOHOOK_KEY_BROWSER_FAVORITES,
  KEY_KATAKANA: IOHOOK_KEY_KATAKANA,
  KEY_UNDERSCORE: IOHOOK_KEY_UNDERSCORE,
  KEY_FURIGANA: IOHOOK_KEY_FURIGANA,
  KEY_KANJI: IOHOOK_KEY_KANJI,
  KEY_HIRAGANA: IOHOOK_KEY_HIRAGANA,
  KEY_YEN: IOHOOK_KEY_YEN,
  KEY_KP_COMMA: IOHOOK_KEY_KP_COMMA,
  KEY_SUN_HELP: IOHOOK_KEY_SUN_HELP,
  KEY_SUN_STOP: IOHOOK_KEY_SUN_STOP,
  KEY_SUN_PROPS: IOHOOK_KEY_SUN_PROPS,
  KEY_SUN_FRONT: IOHOOK_KEY_SUN_FRONT,
  KEY_SUN_OPEN: IOHOOK_KEY_SUN_OPEN,
  KEY_SUN_FIND: IOHOOK_KEY_SUN_FIND,
  KEY_SUN_AGAIN: IOHOOK_KEY_SUN_AGAIN,
  KEY_SUN_UNDO: IOHOOK_KEY_SUN_UNDO,
  KEY_SUN_COPY: IOHOOK_KEY_SUN_COPY,
  KEY_SUN_INSERT: IOHOOK_KEY_SUN_INSERT,
  KEY_SUN_CUT: IOHOOK_KEY_SUN_CUT,
  KEY_UNDEFINED: IOHOOK_KEY_UNDEFINED,
  MOUSE_NOBUTTON: IOHOOK_MOUSE_NOBUTTON,
  MOUSE_BUTTON1: IOHOOK_MOUSE_BUTTON1,
  MOUSE_BUTTON2: IOHOOK_MOUSE_BUTTON2,
  MOUSE_BUTTON3: IOHOOK_MOUSE_BUTTON3,
  MOUSE_BUTTON4: IOHOOK_MOUSE_BUTTON4,
  MOUSE_BUTTON5: IOHOOK_MOUSE_BUTTON5,
};
